### ISSUE TITLE
Meta: Scientific Python macOS Stack

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#16215]
This issue is a multi-months experience report on getting a pretty standard scientific software stack up on macOS. Thank you to @LDAmorim for trying and reporting all things in a dedicated manner. You are the best! :sparkles: 
Thank you also already to everyone that helped us in the last months, you rock :rocket: 

### Setup a Compiler

The first steps are already problematic.
`Clone`-and-go is not really an option even on the latest macOS Catalina, too many things are just GCC specific. One can document this, to ease the pain.

Users will try to bootstrap a GCC with `spack install gcc`. This usually/often/randomly(?) will fail when bootstrapping from AppleClang (latest test: works :tada:). The Slack-level work-around is to use `brew install gcc` and register that. If that's the only way to get started, then let's document that.

Alternatively, let's try to get dependency/package issues fixed with AppleClang.

### The Software Stack

```
spack install py-jupyter
spack install py-scipy
spack install py-matplotlib
spack install py-docutils
spack install py-packaging
spack install py-sympy
spack install py-mpi4py
spack install py-sphinx
spack install py-sphinxcontrib-programoutput
spack install py-sphinx-rtd-theme
spack install graphviz
spack install git
spack install mercurial
spack install subversion
```

### Related Issues

So far, half of the newly reported issue were solvable. Other related macOS + GCC issues (among other open ones in which the user participates):

- https://github.com/spack/spack/issues?q=is%3Aissue+author%3Aldamorim+

Still challenging are even some basics:
- `python` itself: https://github.com/spack/spack/issues/2230#issuecomment-614293185
- `py-setuptools` https://github.com/ax3l/spack-emacs/runs/606176488?check_suite_focus=true
- `py-numpy` does not build without disabling blas and lapack
- `openblas`: IIRC, the source issue for `py-numpy`
- `py-jupyter` https://github.com/spack/spack/issues/15410 (and below)
- `glib` https://github.com/spack/spack/issues/16214

### Time to Solution

Just to mention, build times on Apple laptops for python stacks are problematic, in part since people keep older hardware (but with recent OS versions) for (too) many years and in part because all laptop build times are problematic (a maximum of 4 physical cores is what most people have these days).

A single issue down the stack rebuilds many large dependencies such as `llvm` regularly, since such huge projects are used in many popular python packages. One cannot understate what an influence build caches for macOS would have.

### Impact

macOS developer laptops are (for me) surprisingly common, for example more than half of our group develops on one. So covering common stacks reliably will have a large impact. (Memo to myself: `*Apply nudge to all of you to switch to Linux now. You are all just using a GNU/Linux software stack in an expensive case :-p *` Back to topic?)

### Information on your system

macOS 10.15 Catalina

**Comment by ax3l** [comment]
Added a new nightly (1AM) running CI repo that tries to install selected macOS software with and without Brew's GCC: https://github.com/spack/macos-nightly

Currently covers:
- py-jupyter
- py-scipy
- py-sympy
- py-mpi4py

Here is where its first build fails: https://github.com/spack/macos-nightly/actions/runs/84172846

**Comment by adamjstewart** [comment]
I use a similar stack on macOS Catalina pretty regularly: https://github.com/adamjstewart/dotfiles/blob/master/.spack/darwin/spack.yaml

I agree the biggest pain point is reinstalling dependencies (I currently have 15 different versions of Python installed just since Catalina was released, and consequently 15+ different versions of every Python package). Can't wait for the new concretizer to resolve this.

I'm using a mixed compiler setup with a Spack-installed GCC 9.2.0 for Fortran and the system Apple Clang 11.0.3 for C/C++. I haven't had issues with this. The only issue I've had is that Apple Clang 11.0.3 contains a bug and now I can't build PyTorch anymore.

I use Intel MKL (externally installed) as my BLAS/LAPACK, and have never had an issue with setuptools/numpy. What issue were you seeing exactly?

**Comment by LDAmorim** [comment]
Thanks @ax3l for summarizing this issues!
My build system is very similar to yours, @adamjstewart , and I think the issue was initially: https://github.com/spack/spack/issues/16028, then I ended up trying the `intel-mkl` external package, but I got something identical to  https://github.com/spack/spack/issues/12628 when building my codes (which use Geant4, for example). So I ended up trying multiple workarounds and found (thanks to @ax3l !) that I could just remove the BLAS/LAPACK links (which I actually don't understand how they are not already in macOS - aren't hey already in every linux system?).
Sorry if I'm being confusing please feel free to ask me, I got a bit lost between solving some issues as I still only understand a little bit of what happens as each package is installed via spack.
Thanks for all the great support @adamjstewart and @ax3l !

**Comment by ax3l** [comment]
Python 3.7.7 just landed in Spack yesterday #16170 ~~[fixes a framework issue on macOS](https://github.com/spack/spack/issues/2230#issuecomment-617431516).~~ dang, this bug fix is in Python 3.7.0+

Offline discussed: @LDAmorim (already using Python 3.7.6) will rebuild the stack this night with that latest python. (I am already building it [here](https://github.com/spack/macos-nightly/runs/606624764?check_suite_focus=true) since a few hours.)

- https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-7-final
  - `bpo-28440`: No longer add /Library/Python/3.x/site-packages to sys.path for macOS framework builds to avoid future conflicts. (in 3.7.0+)
  - https://bugs.python.org/issue28440

Still failing on `py-setuptools` (aka the first package that uses CPython) with `python@3.7.7`: https://github.com/spack/macos-nightly/runs/606624706?check_suite_focus=true

**Comment by ax3l** [comment]
After investigating further, there is currently no way to build a *working* CPython with GCC on macOS.

- https://github.com/spack/spack/pull/16222
- https://github.com/python/cpython/pull/13306
- https://bugs.python.org/issue26317

I think the way forward is
- add a `%gcc platform=darwin` conflict to the `python` package until upstream issues are resolved (obj-C file extension on Darwin)
- compile everything with AppleClang from XCode on macOS
- fix all things that pop up... ([first broad compile: https://github.com/spack/macos-nightly/actions/runs/84901942](https://github.com/spack/macos-nightly/actions/runs/84901942))

**Comment by adamjstewart** [comment]
I agree, in my experience a lot of things simply don't work with GCC on macOS, including Python. We should add a conflict for this (if you submit a PR I'll merge it). I would never recommend using a compiler other than Clang + GFortran on macOS. We could be more explicit about this in the Getting Started docs.

**Comment by LDAmorim** [comment]
Hi all, Thank you for these updates.
I tried to test the macOS GCC build with the current develop branch of spack. And I still get the issue reported in https://github.com/spack/spack/issues/12644.
[spack-build-env.txt](https://github.com/spack/spack/files/4517443/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4517444/spack-build-out.txt)
I will test tonight the Clang + GFortran on macOS installation and report back on what I do/find.

**Comment by adamjstewart** [comment]
> I still get the issue reported in #12644.

Do you have the wrong issue number?

**Comment by LDAmorim** [comment]
I think it is the one I meant to mention.
I try to build cmake with GCC and I get the error message:
```
cmake-3.17.0-6wgn25e2m5eyaugd3mml6i5qxm23j7lj/spack-src/Utilities/cmlibuv/src/unix/darwin-proctitle.c:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modified 'bytes' at file scope
  193 |  char bytes[kAuthorizationExternalFormLength];
      |       ^~~~~
```
As is in that issue and in my out file. I think. Maybe I got confused, sorry!

**Comment by hartzell** [comment]
@adamjstewart -- Thanks for sharing your `spack.yaml`

Are the constraints and etc in the sibling `packages.yaml` file used automagically when you build an environment with that `spack.yaml` file or do/would you need to explicitly reference them in a packages section?

**Comment by adamjstewart** [comment]
Yes, they are used automagically. All `*.yaml` files in all config scopes are merged in order of precedence to determine the concretization.

**Comment by ax3l** [comment]
We now changed mode to try the whole stack up with AppleClang 11.0 on macOS catalina.

Things look better, but it's likely python is lacking a dependency when it gets statically linked against `llvm` objects (gettext again? looks like internationalization libs: #16246).

Yes, I'll submit conflict PRs against CMake and CPython: #16249

**Comment by adamjstewart** [comment]
It would be really cool to get the full Anaconda stack of packages building in Spack and have some semi-regular CI to make sure they don't break. This would be the packages in [this list](https://docs.anaconda.com/anaconda/packages/py3.7_osx-64/) with a check in the rightmost column.

**Comment by ax3l** [comment]
Agreed, just note that the anaconda "default" stack is pretty much outdated. Anything recent and useful is pulled with own compiler toolchains and fully self-contained builds from conda-forge packages these days. On conda-forge, all macOS software is built with AppleClang, too. Homebrew follows the same approach. (Just my two cents.)

**Comment by adamjstewart** [comment]
Fair enough, I noticed PyTorch and TensorFlow don't even make the cut for "default" packages.

**Comment by ax3l** [comment]
LLVM +lldb and Qt+OpenGL build issues fixed for macOS and AppleClang now.

Let's see how far we get with building `py-jupyter` on `develop`: https://github.com/spack/macos-nightly/actions/runs/88602977 :crossed_fingers: :rocket:

**Comment by ax3l** [comment]
Update: somewhat varying in time, one job ran into the default timeout (now increased and resubmitted) yet the nightly cronjob already passed :rocket: :sparkles: 
https://github.com/spack/macos-nightly/actions/runs/88628149

[We are in green territory now!](https://github.com/spack/macos-nightly)
[![spack macOS Python](https://github.com/spack/macos-nightly/workflows/spack%20macOS%20Python/badge.svg?branch=master)](https://github.com/spack/macos-nightly)

**Comment by LDAmorim** [comment]
> After investigating further, there is currently no way to build a _working_ CPython with GCC on macOS.
> 
> * #16222
> * [python/cpython#13306](https://github.com/python/cpython/pull/13306)
> * https://bugs.python.org/issue26317
> 
> I think the way forward is
> 
> * add a `%gcc platform=darwin` conflict to the `python` package until upstream issues are resolved (obj-C file extension on Darwin)
> * compile everything with AppleClang from XCode on macOS
> * fix all things that pop up... ([first broad compile: https://github.com/spack/macos-nightly/actions/runs/84901942](https://github.com/spack/macos-nightly/actions/runs/84901942))

Hi all,

This is just an update in case people are getting stuck on this detail.

There is a problem now with the inclusion of the conflict, even if I define:
```console
$ cat ~/.spack/darwin/packages.yaml                 
packages:
  cmake:
    buildable: False
    paths:
      cmake@3.18.1: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/cmake-3.18.1-u4guucbahyuq5pswf55b2ebqslsjub7m
  all:
    providers:
      mpi: [mpich, openmpi]
```

When I try to install `openpmd-api@dev %gcc` it fails due to the conflict.

I had to comment out the conflict in the package config of `cmake` and use that one as an external package, to be able to do that installation.

So, maybe instead of a `conflict` we could write a warning only.

So users of macOS would know how to use the current versions of the packages correctly.

Cheers,
Diana

**Comment by becker33** [comment]
@LDAmorim the issue of conflicts being raised for external packages was fixed 4 days ago in #18183.

**Comment by ax3l** [comment]
Awesome. I am also updating the newly introduced support for `cmake %gcc` in 3.18.0 via #18253
Update: nope, more things to do upstream: https://gitlab.kitware.com/cmake/cmake/-/issues/21135

CPython though does still not look like it will have GCC support on macOS in 3.9.0: https://bugs.python.org/issue26317

**Comment by adamjstewart** [comment]
GitLab CI now includes several core Python packages. Is this issue still relevant?

**Comment by ax3l** [comment]
Yes, we still have no way to bootstrap MPI packages without relying on a cumbersome "mix in gfortran from some source" bootstrap process.

For instance, getting `py-mpi4py` _on a fresh mac_ to install is not as simple as advertised: https://spack.readthedocs.io

```
$ git clone -c feature.manyFiles=true https://github.com/spack/spack.git
$ cd spack/bin
$ ./spack install py-mpi4py
```

Using GCC for everything on macOS does not work - many essential packages (e.g., CPython) don't test and support GCC on Mac. Even for pure C/C++/Python stacks, using Xcode alone does not work: Xcode lacks a Fortran compiler, but Spack defaults to `+fortran`.

**Comment by adamjstewart** [comment]
There is some interest in building a GitLab CI pipeline for this kind of software, not sure who would be the best person to tackle this.

**Comment by adamjstewart** [comment]
The ML CI stacks pull in most of these packages at this point. Wondering if we can close this, or if we need a dedicated CI stack for this.
