### ISSUE TITLE
acfl vs arm compiler version mismatch

### ISSUE THREAD

**Issue by ashterenli** [LLNL/spack#36545]
This is giving me a headache when using hierarchical modules.

```
$ ls modulefiles/linux-amzn2-aarch64/Core/acfl/
22.0.2.lua  22.1.lua
```

but

```
$ spack compilers
==> Available compilers
-- arm amzn2-aarch64 --------------------------------------------
arm@22.1.0.12  arm@22.0.2.1776
```

I can resolve the name conflict with e.g.

```
projections:
    acfl: 'arm/{version}'
```

which will give me 
```
$ ls modulefiles/linux-amzn2-aarch64/Core/arm/
22.0.2.lua  22.1.lua
```

but all my packages built with the arm compiler are still
in different dirs:

```
$ ls modulefiles/linux-amzn2-aarch64/arm/
22.0.2.1776  22.1.0.12
```

So when I load an arm compiler module, I don't see any modules for packages built with it.

How best to resolve this?

**Comment by annop-w** [comment]
@ashterenli This should be solved by #36768 and also acfl 23.04 is now in Spack. Could you please try the fix ? Please let me know if there are more problems.

**Comment by ashterenli** [comment]
@annop-w Thank you. I don't know yet the spack releases policy. Will this fix be merged into 0.19.2? Or do I need to follow the head to see it?

**Comment by annop-w** [comment]
@ashterenli The commit is not yet merged. I believe this targets 0.20.0. Meanwhile, you can try pulling the commit from my fork and experiment with it. I'm curious to know if it solves all the problems you mentioned or not.

**Comment by ashterenli** [comment]
I get:
```
+ spack install acfl@23.04 %gcc@7.3.1
==> Installing acfl-23.04-z5th5psvhhir5ysplxsn4372lcxegruv
==> No binary for acfl-23.04-z5th5psvhhir5ysplxsn4372lcxegruv found: installing from source
==> Fetching https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/23-04/arm-compiler-for-linux_23.04_AmazonLinux-2_aarch64.tar
==> No patches needed for acfl 
==> acfl: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './arm-compiler-for-linux_23.04_AmazonLinux-2.sh' '--accept' '--force' '--install-to' '/bm/sw_spack_head/spack-head/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_/linux-amzn2-neoverse_v1/gcc-7.3.1/acfl-23.04-z5th5psvhhir5ysplxsn4372lcxegruv'
2 errors found in build log:
     76    warning: Unable to get systemd shutdown inhibition lock
     77    Preparing packages...
     78    gcc-12.2.0-AmazonLinux-2-12.2.0-288.aarch64
     79    arm-linux-compiler-23.04-AmazonLinux-2-23.04-21.aarch64
     80    arm-compiler-for-linux-23.04-AmazonLinux-2-23.04-29.aarch64
     81    armpl-23.04.0-AmazonLinux-2-arm-linux-compiler-23.04.0-21.aarch64
  >> 82    error: unpacking of archive failed on file /bm/sw_spack_head/spack-h
           ead/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/
           __spack_path_placeholder__/__spack_/linux-amzn2-neoverse_v1/gcc-7.3.
           1/acfl-23.04-z5th5psvhhir5ysplxsn4372lcxegruv/armpl-23.04.0_AmazonLi
           nux-2_arm-linux-compiler/lib/libarmpl_int64.a;643e363c: cpio: write 
           failed - No such file or directory
  >> 83    error: armpl-23.04.0-AmazonLinux-2-arm-linux-compiler-23.04.0-21.aar
           ch64: install failed
     84    armpl-23.04.0-AmazonLinux-2-gcc-23.04.0-21.aarch64
     85    Installation failed. The uninstalled package files have been left in
            /bm/tmpdir/extract.PjAwZB.
     86    You can attempt a manual install of these files, do you wish to keep
            them? Cleaning up install files in /bm/tmpdir/extract.PjAwZB

```

The log file does not show any more info:
```
Arm document version 1.0, effective 24 June 2020



Unpacking...
Installing...warning: Unable to get systemd shutdown inhibition lock
warning: Unable to get systemd shutdown inhibition lock
warning: Unable to get systemd shutdown inhibition lock
warning: Unable to get systemd shutdown inhibition lock
warning: Unable to get systemd shutdown inhibition lock
warning: Unable to get systemd shutdown inhibition lock
Preparing packages...
gcc-12.2.0-AmazonLinux-2-12.2.0-288.aarch64
arm-linux-compiler-23.04-AmazonLinux-2-23.04-21.aarch64
arm-compiler-for-linux-23.04-AmazonLinux-2-23.04-29.aarch64
armpl-23.04.0-AmazonLinux-2-arm-linux-compiler-23.04.0-21.aarch64
error: unpacking of archive failed on file /bm/sw_spack_head/spack-head/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_/linux-amzn2-neoverse_v1/gcc-7.3.1/acfl-23.04-z5th5psvhhir5ysplxsn4372lcxegruv/armpl-23.04.0_AmazonLinux-2_arm-linux-compiler/lib/libarmpl_int64.a;643e363c: cpio: write failed - No such file or directory
error: armpl-23.04.0-AmazonLinux-2-arm-linux-compiler-23.04.0-21.aarch64: install failed
armpl-23.04.0-AmazonLinux-2-gcc-23.04.0-21.aarch64
```

**Comment by ashterenli** [comment]
Also, I still see:

```
$ spack compilers
==> Available compilers
-- arm amzn2-aarch64 --------------------------------------------
arm@22.1.0.12
```
which does not match the acfl module version:

```
$ ls modulefiles/linux-amzn2-aarch64/Core/acfl/
22.1.lua
```

**Comment by annop-w** [comment]
> Unable to get systemd shutdown inhibition lock

This seems like an error on your system. Can you `yum update` or `yum install` anything ? 

> -- arm amzn2-aarch64 --------------------------------------------
arm@22.1.0.12

Please make sure that you have the commit `2d6fee50d319f6a5844dc29e5d6afda257b31d68` from my fork. Then, perhaps try to remove your older installation, e.g. `spack compiler remove arm@22.1.0.12` and re-install `acfl@22.1`. `spack load acfl@22.1` followed by `spack compiler find` should give you

```
==> Available compilers
-- arm amzn2-aarch64 --------------------------------------------
arm@23.04  arm@22.1

-- gcc amzn2-aarch64 --------------------------------------------
gcc@7.3.1
```
I've just tried this in AmazonLinux2 docker container. Please let me know if there are still problems.

**Comment by ashterenli** [comment]
ah sorry, I missed that you haven't commited to head yet.
How can I apply your commit?

**Comment by annop-w** [comment]
You can do
```
git remote add annop-w https://github.com/annop-w/spack.git
git fetch annop-w arm
git cherry-pick 2d6fee5
```

**Comment by ashterenli** [comment]
amazing, thank you!

```
$ spack compilers
==> Available compilers
-- arm amzn2-aarch64 --------------------------------------------
arm@23.04  arm@22.1
```

**Comment by ashterenli** [comment]
and I can build packages with both these arm compilers, so the modules seem to be fixed too. Thank you again.

**Comment by annop-w** [comment]
No problem. Glad to know all is fixed 😃
