### ISSUE TITLE
Installation issue: LLVM on Apple Silicon

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#39713]
### Steps to reproduce the issue

```console
> spack spec -I llvm@14.0.6
Input spec
--------------------------------
 -   llvm@14.0.6

Concretized
--------------------------------
 -   llvm@14.0.6%apple-clang@14.0.3+clang~code_signing~cuda~flang~gold~ipo~libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3 build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime patches=1f42874,25bc503,8248141,b216cff,cb8e645 shlib_symbol_version=none targets=all version_suffix=none arch=darwin-ventura-m2
[+]      ^cmake@3.26.3%apple-clang@14.0.3~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=darwin-ventura-m2
[+]          ^openssl@1.1.1t%apple-clang@14.0.3~docs~shared build_system=generic certs=mozilla arch=darwin-ventura-m2
[+]              ^ca-certificates-mozilla@2023-01-10%apple-clang@14.0.3 build_system=generic arch=darwin-ventura-m2
[+]      ^hwloc@2.9.0%apple-clang@14.0.3~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl~pci~rocm build_system=autotools libs=shared,static arch=darwin-ventura-m2
[+]          ^gnuconfig@2022-09-17%apple-clang@14.0.3 build_system=generic arch=darwin-ventura-m2
[+]          ^pkgconf@1.8.0%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]      ^libedit@3.1-20210216%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]      ^libxml2@2.10.3%apple-clang@14.0.3~python build_system=autotools arch=darwin-ventura-m2
[+]          ^libiconv@1.17%apple-clang@14.0.3 build_system=autotools libs=shared,static arch=darwin-ventura-m2
[+]      ^lua@5.3.6%apple-clang@14.0.3~pcfile+shared build_system=makefile fetcher=curl arch=darwin-ventura-m2
[+]          ^curl@8.0.1%apple-clang@14.0.3~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=secure_transport arch=darwin-ventura-m2
[+]              ^nghttp2@1.52.0%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^readline@8.2%apple-clang@14.0.3 build_system=autotools patches=bbf97f1 arch=darwin-ventura-m2
[+]          ^unzip@6.0%apple-clang@14.0.3 build_system=makefile arch=darwin-ventura-m2
[+]      ^ncurses@6.4%apple-clang@14.0.3~symlinks+termlib abi=none build_system=autotools arch=darwin-ventura-m2
[+]      ^ninja@1.11.1%apple-clang@14.0.3+re2c build_system=generic arch=darwin-ventura-m2
[+]          ^python@3.10.10%apple-clang@14.0.3+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis+optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=darwin-ventura-m2
[+]              ^gettext@0.21.1%apple-clang@14.0.3+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=darwin-ventura-m2
[+]                  ^tar@1.34%apple-clang@14.0.3 build_system=autotools zip=pigz arch=darwin-ventura-m2
[+]                      ^zstd@1.5.4%apple-clang@14.0.3~ipo+programs build_system=cmake build_type=RelWithDebInfo compression=none generator=make libs=shared,static arch=darwin-ventura-m2
[+]                          ^cmake@3.26.1%apple-clang@14.0.3~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=darwin-ventura-m2
[+]                          ^gmake@4.4.1%apple-clang@14.0.3~guile build_system=autotools arch=darwin-ventura-m2
[+]          ^re2c@2.2%apple-clang@14.0.3 build_system=generic arch=darwin-ventura-m2
[+]      ^perl-data-dumper@2.173%apple-clang@14.0.3 build_system=perl arch=darwin-ventura-m2
[+]          ^perl@5.36.0%apple-clang@14.0.3+cpanm+open+shared+threads build_system=generic arch=darwin-ventura-m2
[+]              ^berkeley-db@18.1.40%apple-clang@14.0.3+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-ventura-m2
[+]      ^pkgconf@1.9.5%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]      ^python@3.11.4%apple-clang@14.0.3+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis+optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,f2fd060 arch=darwin-ventura-m2
[e]          ^apple-libuuid@1353.100.2%apple-clang@14.0.3 build_system=bundle arch=darwin-ventura-m2
[+]          ^bzip2@1.0.8%apple-clang@14.0.3~debug~pic+shared build_system=generic arch=darwin-ventura-m2
[+]              ^diffutils@3.9%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^expat@2.5.0%apple-clang@14.0.3~libbsd build_system=autotools arch=darwin-ventura-m2
[+]          ^gdbm@1.23%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^gettext@0.21.1%apple-clang@14.0.3+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=darwin-ventura-m2
[+]              ^tar@1.34%apple-clang@14.0.3 build_system=autotools zip=pigz arch=darwin-ventura-m2
[+]                  ^pigz@2.7%apple-clang@14.0.3 build_system=makefile arch=darwin-ventura-m2
[+]                  ^zstd@1.5.5%apple-clang@14.0.3+programs build_system=makefile compression=none libs=shared,static arch=darwin-ventura-m2
[+]          ^libffi@3.4.4%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^libxcrypt@4.4.33%apple-clang@14.0.3~obsolete_api build_system=autotools arch=darwin-ventura-m2
[+]          ^sqlite@3.40.1%apple-clang@14.0.3+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=darwin-ventura-m2
[+]      ^swig@4.0.2-fortran%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^autoconf@2.69%apple-clang@14.0.3 build_system=autotools patches=35c4492,7793209,a49dd5b arch=darwin-ventura-m2
[+]              ^m4@1.4.19%apple-clang@14.0.3+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=darwin-ventura-m2
[+]                  ^libsigsegv@2.14%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^automake@1.16.5%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]              ^autoconf@2.69%apple-clang@14.0.3 build_system=autotools patches=35c4492,7793209,a49dd5b arch=darwin-ventura-m2
[+]                  ^m4@1.4.19%apple-clang@14.0.3+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=darwin-ventura-m2
[+]          ^bison@3.8.2%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^libtool@2.4.7%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m2
[+]          ^pcre@8.45%apple-clang@14.0.3~jit+multibyte+utf build_system=autotools arch=darwin-ventura-m2
[+]      ^xz@5.4.1%apple-clang@14.0.3~pic build_system=autotools libs=shared,static arch=darwin-ventura-m2
[+]      ^zlib@1.2.13%apple-clang@14.0.3+optimize+pic+shared build_system=makefile arch=darwin-ventura-m2
```
I need LLVM 14 for py-llvmlite, I can't use a newer version.

### Error message

<details><summary>Error message</summary>

<pre>
FAILED: openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o 
/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-build-zumwal5/./bin/clang++ --target=arm64-apple-darwin22.6.0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Domp_EXPORTS -I/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-build-zumwal5/runtimes/runtimes-bins/openmp/runtime/src -I/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src -I/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src/i18n -I/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src/include -I/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src/thirdparty/ittnotify -I/Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/hwloc-2.9.0-tslipxegaqlt4a4ylsrk4x3zof74rjv6/include -std=c++11 -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -Wall -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-extra -Wno-pedantic -std=c++14 -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -fPIC   -D _GNU_SOURCE -D _REENTRANT -fno-exceptions -fno-rtti -Wno-covered-switch-default -Wno-frame-address -Wno-strict-aliasing -Wno-switch -Wno-uninitialized -Wno-unused-but-set-variable -Wno-return-type-c-linkage -Wno-cast-qual -Wno-int-to-void-pointer-cast -MD -MT openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o -MF openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o.d -o openmp/runtime/src/CMakeFiles/omp.dir/kmp_debug.cpp.o -c /private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src/kmp_debug.cpp
In file included from /private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src/kmp_debug.cpp:13:
/private/var/folders/jv/cgkfvslj6nq1l7cw0c8c_8gm0000gn/T/Adam/spack-stage/spack-stage-llvm-14.0.6-zumwal5pvyvcol55gfdig2kkjmkegjjg/spack-src/openmp/runtime/src/kmp.h:69:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
1 error generated.
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (8d90933781c1bd27570ed129e6cbe219d7f2abb0)
* **Python:** 3.10.10
* **Platform:** darwin-ventura-m2
* **Concretizer:** clingo

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/12480191/spack-build-out.txt)
* [spack-build-env-mods.txt](https://github.com/spack/spack/files/12480193/spack-build-env-mods.txt)

@haampie  @skosukhin  @trws

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by aumuell** [comment]
To add a data point: slight variations of your spec built fine on darwin-ventura-m1:
- `libcxx=none` instead of `libcxx=runtime`
- `openmp=project` instead of `openmp=runtime`

**Comment by adamjstewart** [comment]
It worked! Any idea which change was required and why? Maybe we could add a conflict.

**Comment by adamjstewart** [comment]
I was able to successfully build LLVM using those suggested changes, but llvmlite failed immediately afterwards:
```
> spack install py-llvmlite
...
  In file included from assembly.cpp:1:
  In file included from /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/include/llvm/AsmParser/Parser.h:16:
  In file included from /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/include/llvm/ADT/STLExtras.h:20:
  In file included from /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/include/llvm/ADT/Optional.h:19:
  In file included from /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/include/llvm/ADT/Hashing.h:47:
  In file included from /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/include/llvm/Support/DataTypes.h:19:
  In file included from /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/include/llvm-c/DataTypes.h:27:
  /Users/Adam/spack/opt/spack/darwin-ventura-m2/apple-clang-14.0.3/llvm-14.0.6-kl5l3ibp3vt2hgdr6b3jxediso765kf6/lib/clang/14.0.6/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  #include_next <inttypes.h>
                ^~~~~~~~~~~~
```

**Comment by naromero77** [comment]
I am likely being Captain Obvious here, but I have run into stuff like this with newer version of LLVM as well. I think the problem gets back to not capturing some dependencies in Spack that LLVM needs.

I don't know much about Apple OS, but a lot of Linux distribution have a main package (foo) and a accompanying developer package (foo-devel). The header files that are needed for LLVM end up being in the `foo-devel`.

I do have an Apple M1 (personal machine), but don't have Spack on it. I don't know if there is some way to simulate the Apple M1 environment on some type of virtual machine, so I can take a look at this more closely.

**Comment by skosukhin** [comment]
`inttypes.h` is a standard C header. From https://github.com/spack/spack/issues/39713#issuecomment-1702255468, I assume that the header is available on the system but not in a directory that the newly built compiler is searching for the headers by default. I wonder how the problem is solved upstream. Probably, they extend the default search list in some way at the build time.

**Comment by adamjstewart** [comment]
On my system, this file is found in:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/inttypes.h
```
The most recent version of Xcode changed the linker such that it no longer looks in the default directories. I tried using:
```python
def setup_build_environment(self, env):
    if self.spec.satisfies("%apple-clang@15:"):                                                 
        env.append_flags("LDFLAGS", "-Wl,-ld_classic")    
```
but this didn't seem to solve the problem. The error message seems similar to https://github.com/numba/llvmlite/issues/856, but it also feels like a generic error message meaning "something is wrong with LLVM".
