### ISSUE TITLE
Compatibility of Xcode 16+ ld and Spack's compiler wrappers

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#46506]
### Steps to reproduce

It's possible there is a compatibility issue between Spack's compiler wrappers and the `ld` provided by Xcode 16+. Xcode 15 introduced a new linker that is much more strict than previous versions. Xcode 16 (released this week) updated this linker to be even more strict, disallowing duplicate RPATHs.

If I understand correctly, Spack's compiler wrappers add RPATHs for all `<prefix>/lib` directories regardless of whether or not RPATH linker args are already present on the command line. If this is correct, I think we just need to prevent duplicate RPATHs in the compiler wrappers.

### Error message

After upgrading to Xcode 16, I see a number of issues like the following affecting packages like cgns, hdf5, py-h5py, VTK, py-torchvision, etc.
```
ld: warning: duplicate -rpath '/Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/cgns-4.4.0-hyx7mtf6mxo7h7gz5rx4lthyrypp4u7h/lib' ignored
ld: warning: duplicate -rpath '/Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/hdf5-1.14.3-emur2bgnslki3qnnmeqoo5ehaeyeseq5/lib' ignored
ld: duplicate LC_RPATH '/Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/hdf5-1.14.3-emur2bgnslki3qnnmeqoo5ehaeyeseq5/lib' in '/Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/cgns-4.4.0-hyx7mtf6mxo7h7gz5rx4lthyrypp4u7h/lib/libcgns.4.4.dylib'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
My best guess is that the build system adds RPATH on its own, and Spack's compiler wrappers also add RPATH, and the new `ld` fails with duplicate RPATHs.

The current workaround is to add `-Wl,-ld_classic` to the compiler flags. However, this has a warning message saying that `ld_classic` is deprecated and will be removed in the future.

### Information on your system

* **Spack:** 0.23.0.dev0 (28e3295fb04d8d502b2fae7894f1942af86875aa)
* **Python:** 3.11.9
* **Platform:** darwin-sequoia-m2

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

Related to #46460, #46462, and #46463

**Comment by adamjstewart** [comment]
Fixing PR was reverted, so this is still an issue.

**Comment by haampie** [comment]
I can see from the build output of cgns the following:

```
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib/libcgns.4.4.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib/libcgns.4.4.dylib (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnscheck
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnscheck (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnsconvert
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnsconvert (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnsdiff
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnsdiff (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnslist
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnslist (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnsnames
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnsnames (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
-- Installing: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnscompress
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/bin/cgnscompress (for architecture arm64) option "-add_rpath /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib" would duplicate path, file already has LC_RPATH for: /Users/harmenstoppels/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/cgns-4.4.0-5bpz56hkdeqicoqokzp7myzty5to7f3b/lib
```

which is not fatal, and does not result in duplicate rpaths.

Can you share build logs of cgns? What CMake version did you use?

**Comment by haampie** [comment]
I can't reproduce a build of cgns on macOS sequoia using the latest xcode 16 where `libcgns.4.4.dylib` has a repeated rpath.

**Comment by adamjstewart** [comment]
I can no longer reproduce this issue either (other than with torchvision). Since this is no longer a widespread issue, let's close and try to fix torchvision.

**Comment by adamjstewart** [comment]
Could also be related to #45479, I'm using:
```yaml
compilers:
- compiler:
    spec: apple-clang@=16.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/gfortran/bin/gfortran
      fc: /usr/local/gfortran/bin/gfortran
    flags: {}
    operating_system: sequoia
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths:
    - /usr/local/gfortran/lib
```
and others have also reported issues with duplicate rpaths.

**Comment by adamjstewart** [comment]
py-torchaudio has the same issue, likely all libraries that link to PyTorch.

**Comment by billsacks** [comment]
@adamjstewart - I am running into a similar issue: when using Apple's clang (v. 16) as a linker for a mixed Fortran/C++ program, I'm getting a `duplicate LC_RPATH` error. I am new to spack, and it's possible that this is user error on my part, but I have boiled this down to a simple reproducer, so I thought I'd share this in case it's helpful:

With a recent version of spack (7f0bb714):
```bash
. share/spack/setup-env.sh
# Using gcc 14.1.0 instead of latest due to the issue noted in https://github.com/spack/spack/issues/45628
spack install gcc@14.1.0
spack load gcc
gfortran -c -o hellof.o hellof.f90
gfortran -dynamiclib -o libhellof.dylib hellof.o
clang -c -o helloc.o helloc.c
clang -o hello helloc.o -L . -lhellof
```

where `hellof.f90` is simply:
```fortran
subroutine hello_world
   print *, 'Hello world'
end subroutine hello_world
```

and `helloc.c` is simply:
```c
#include <stdio.h>
int main()
{
   printf("Hello World");
   return 0;
}
```

This fails with:
```
ld: duplicate LC_RPATH '/Users/sacks/temporary/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/gcc-14.1.0-wtlmo4cr3lqxl6tnnue7tci4eiiejfhd/lib' in '/Users/sacks/temporary/libhellof.dylib'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And indeed, `otool -l libhellof.dylib` gives two instances of the following LC_RPATH entries:
```
/Users/sacks/temporary/spack/opt/spack/darwin-sonoma-m1/apple-clang-16.0.0/gcc-14.1.0-wtlmo4cr3lqxl6tnnue7tci4eiiejfhd/lib
```

I don't have this problem when using homebrew-installed gcc (though I'm using 13.2 rather than 14.1 through homebrew).

**Comment by billsacks** [comment]
I also tried this with the changes in https://github.com/spack/spack/pull/46264 (thinking that might be what resolves this issue), but that didn't help. (That test was on top of a slightly older version of spack: develop-2024-11-10.)

**Comment by adamjstewart** [comment]
^ @Chrismarsh @tgamblin @haampie

**Comment by adamjstewart** [comment]
Also just hit this issue with VTK.

**Comment by Chrismarsh** [comment]
@billsacks The PR in https://github.com/spack/spack/pull/46264 fixes the problem where a user-specified RPATH is added to a static library link-line. Are you adding a user-specific rpath? I add an extra rpath as detailed here https://github.com/spack/spack/issues/45479

I've pushed a rebased version of https://github.com/spack/spack/pull/46264 -- maybe try that? I use this PR daily to solve this problem.

@haampie had asked that I put together a reproducible issue and I have done so https://github.com/spack/spack/issues/47570. 

edit: adam what VTK version?

**Comment by adamjstewart** [comment]
> @haampie what VTK version?

Guessing this is meant for me. VTK 9.3.1. Build log contains things like:
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/vtk-9.3.1-y3tzuypvliexstikzhk2bvrhqyz6qpeu/lib/libvtkWrappingTools-9.3.9.3.dylib (for architecture arm64) option "-add_rpath /Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/vtk-9.3.1-y3tzuypvliexstikzhk2bvrhqyz6qpeu/lib" would duplicate path, file already has LC_RPATH for: /Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/vtk-9.3.1-y3tzuypvliexstikzhk2bvrhqyz6qpeu/lib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/vtk-9.3.1-y3tzuypvliexstikzhk2bvrhqyz6qpeu/lib/libvtkWrappingTools-9.3.9.3.dylib (for architecture arm64) option "-add_rpath /Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/vtk-9.3.1-y3tzuypvliexstikzhk2bvrhqyz6qpeu/lib64" would duplicate path, file already has LC_RPATH for: /Users/Adam/spack/opt/spack/darwin-sequoia-m2/apple-clang-16.0.0/vtk-9.3.1-y3tzuypvliexstikzhk2bvrhqyz6qpeu/lib64
```
[spack-build-out.txt.gz](https://github.com/user-attachments/files/17923951/spack-build-out.txt.gz)

**Comment by billsacks** [comment]
Thanks for that info, @Chrismarsh . I hadn't understood the context behind #46264, so thanks for clarifying. No, I'm not adding any user-specified rpaths, so it makes sense that that PR doesn't solve this problem for me. In fact, it seems like I may be seeing an issue that's kind of the opposite of yours: it sounds like you need to explicitly specify the rpath to the gcc/gfortran lib when building with clang+gfortran. In my (so far very limited) experience, I did *not* need to explicitly specify any extra rpaths for this use case: spack seems to handle the necessary addition of rpaths automatically on my system, but adds a duplicate copy of this path to the gfortran/gcc lib directory.

**Comment by Chrismarsh** [comment]
@adamjstewart ~~I'm on develop at `141cdb681061b08db260b25b1275a38c4da7fde6` and `spack install vtk@9.3.1 +examples` (that variant to trigger a new build of vtk) did not reproduce that error for me. It did reuse all the existing dependencies. Anything more specific I can try? I don't understand why this problem (seems to?) comes and goes.~~

edit: I forgot to remove `-ld_classic` from my custom flags, which is why I didn't hit this sorry.

Since @tgamblin's PR  https://github.com/spack/spack/pull/47255 was merged in, I haven't had any of these duplicate loader issues building shared libraries. The only issue I have is when building a static library, which https://github.com/spack/spack/pull/46264 fixes. Then @tgamblin originally authored it, https://github.com/spack/spack/pull/46598 also fixed the static library issue, but I am not sure the status of that PR. 

I'm still on Sonoma 14.7.1 because I'm hesitant to update given your experiences. But I am on the same(?) compiler:
```
$ clang++ -v
Apple clang version 16.0.0 (clang-1600.0.26.4) 
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

@billsacks No problem. Yes, that PR only fixes one small problem. What OS are you on? What spec are you building when you hit this?

**Comment by billsacks** [comment]
> What OS are you on? What spec are you building when you hit this?

I'm on Sonoma 14.7. I haven't run into the issue when building anything with spack itself, but rather have run into it when building a multi-language (Fortran/C++) library/application outside of spack, but using a mix of spack's gfortran and Apple's clang. So I'm not entirely sure that my issue is a spack problem, but it did feel like there's something in the way that the spack-built gfortran is set up that is contributing to this issue. (My homebrew-installed gfortran doesn't lead to this issue.)

Which I guess is to say: if people more familiar with spack feel like my issue (https://github.com/spack/spack/issues/46506#issuecomment-2492650588) isn't very relevant here, then feel free to ignore it and I'll try to work around it on my end, but I thought I'd provide it in case it feels like a helpful data point.

**Comment by Chrismarsh** [comment]
@billsacks I /think/ the reason homebrew works and spack doesn't for your example is that homebrew by default adds `-ld_classic` to CXXFLAGS when xcode 15+ is detected (as per https://github.com/Homebrew/homebrew-core/issues/145991#issuecomment-1736508100). I can't find any other reference to this changed defauly behaviour, but this has always been my understanding/impression. If you add `-ld_classic` to your command, it works correctly
```
$ clang -o hello helloc.o -L . -lhellof -ld_classic
ld: warning: -ld_classic is deprecated and will be removed in a future release
$ ./hello
Hello World
```

**Comment by haampie** [comment]
Lots of comments here, going in all directions... Let's focus GitHub issues on specific problems.

I quickly looked at this and found the following:

1. The classic linker does not deduplicate rpaths, which is how people end up with binaries containing repeated rpaths.
   Run for example `printf 'void f(void){}' | gcc -xc - -dynamiclib -o libf.dylib -Wl,-v` and notice `ld-classic`.
2. Linking to dylibs with repeated rpaths using the new linker produces an error, there's no way to ignore this as far as I can see.
3. Spack built GCC uses upstream GCC, which defaults to the classic linker.
4. Iain Sandoe's aarch64-darwin branch is still alive, which is now at GCC 13 with better support for the new linker.

Further:

5. The language fortran is irrelevant to this issue
6. The CMake errors mentioned here are not fatal and as far as I can see irrelevant.

I didn't check yet why vanilla `gcc` generates a link line with repeated rpaths to its runtime libraries.

Finally
 
1. This is a pedantic change by Apple with no clear benefit, only breaking backwards compatibility with existing libraries that happen to have repeated rpaths. It would be good to ask them to turn this into a warning again.
2. Deduplication in the compiler wrapper is not that beneficial since the GCC itself injects rpaths that are not seen by the wrapper, so I don't think we should fix this in Spack at all.
3. I would suggest folks to use Iain's branch and consistently use the new linker instead.

**Comment by haampie** [comment]
Reopening until we've

- [ ] got a ticket upstream with Apple, and 
- [x] updated our GCC recipe to use Iain's branch on macOS 15+, or apply equivalent patches s.t. it uses the new linker by default (like [homebrew does](https://github.com/Homebrew/homebrew-core/blob/e40f362220d2311aa48713988ec25ec6b8275bda/Formula/g/gcc.rb#L15-L18))

**Comment by billsacks** [comment]
Thank you for this great summary, @haampie .

<details>

<summary> Also replying briefly to @Chrismarsh 's recent comment: </summary>

> I /think/ the reason homebrew works and spack doesn't for your example is that homebrew by default adds -ld_classic to CXXFLAGS when xcode 15+ is detected

That may be the case, but my brief investigation suggested another difference as well: Using my homebrew-installed gfortran for:

```
gfortran -c -o hellof.o hellof.f90
gfortran -dynamiclib -o libhellof.dylib hellof.o
otool -l libhellof.dylib
```

showed that the resulting libhellof.dylib did not have any duplicate rpaths (in contrast to my spack-installed gfortran). This might be situation-dependent, though.

My homebrew-installed gfortran shows:

```
Load command 14
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
Load command 15
          cmd LC_RPATH
      cmdsize 96
         path /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13 (offset 12)
Load command 16
          cmd LC_RPATH
      cmdsize 64
         path /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc (offset 12)
Load command 17
          cmd LC_RPATH
      cmdsize 64
         path /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current (offset 12)
```

whereas my spack-installed gfortran shows:

```
Load command 14
          cmd LC_RPATH
      cmdsize 128
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib (offset 12)
Load command 15
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
Load command 16
          cmd LC_RPATH
      cmdsize 168
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0 (offset 12)
Load command 17
          cmd LC_RPATH
      cmdsize 128
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib (offset 12)
```

I realize this is not a total apples-to-apples comparison... e.g., these are on two different machines.

</details>

**Comment by haampie** [comment]
Run `printf 'void f(void){}' | gcc -xc - -dynamiclib -o libf.dylib -Wl,-v` instead to see if duplicate rpaths are injected, and whether or not the classic linker is used by default.

Can you please reduce the verbosity of your comment?

**Comment by billsacks** [comment]
> Can you please reduce the verbosity of your comment?

I see you beat me to it - thanks.

> Run printf 'void f(void){}' | gcc -xc - -dynamiclib -o libf.dylib -Wl,-v instead to see if duplicate rpaths are injected, and whether or not the classic linker is used by default.

I have tried this with spack-installed gcc 14.1, homebrew-installed gcc 13.2, and apple-installed "gcc" that is really clang 16; only spack-installed gcc 14.1 leads to duplicate rpaths in the resulting dylib; details below. 

<details>

### With spack-installed gcc 14.1

This uses ld-classic and results in a duplicate LC_RPATH:
```
$ printf 'void f(void){}' | gcc -xc - -dynamiclib -o libf.dylib -Wl,-v
collect2 version 14.1.0
/Library/Developer/CommandLineTools/usr/bin/ld-classic -demangle -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/ -dynamic -arch arm64 -platform_version macos 14.0.0 0.0 -o libf.dylib -L/Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0 -L/Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0/../../.. -rpath /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib -lemutls_w -lheapt_w /var/folders/gm/7mvxng053xd64jyfp7m9d2mc0000gp/T//ccnsrUnj.o -v -dylib -lgcc -lSystem -no_compact_unwind -rpath @loader_path -rpath /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0 -rpath /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib
@(#)PROGRAM:ld-classic  PROJECT:ld64-954.16
BUILD 07:38:35 Oct  4 2024
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
Library search paths:
	/Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0
	/Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib
	/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
Framework search paths:
	/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/
```

A portion of the output from `otool -l` shows:
```
Load command 11
          cmd LC_RPATH
      cmdsize 128
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib (offset 12)
Load command 12
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
Load command 13
          cmd LC_RPATH
      cmdsize 168
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib/gcc/aarch64-apple-darwin23.6.0/14.1.0 (offset 12)
Load command 14
          cmd LC_RPATH
      cmdsize 128
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.1.0-yxln5vjswuutfxtzpq4tf5yk7iuhin4a/lib (offset 12)
```

### With homebrew-installed gcc 13.2

As far as I can tell, this does *not* use ld-classic, and it does *not* result in duplicate LC_RPATH entries:
```
collect2 version 13.2.0
/usr/bin/ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/ -dynamic -arch arm64 -platform_version macos 14.0.0 0.0 -o libf.dylib -L/opt/homebrew/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin23/13 -L/opt/homebrew/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc -L/opt/homebrew/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/aarch64-apple-darwin23/13/../../.. /var/folders/mp/rlk6q70n1jl_syyghjrhsv7w0000gp/T//ccrwnZXe.o -v -dylib -lemutls_w -lgcc -lSystem -no_compact_unwind -rpath @loader_path -rpath /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13 -rpath /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc -rpath /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current
@(#)PROGRAM:ld PROJECT:ld-1115.7.3
BUILD 07:38:57 Oct  4 2024
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
will use ld-classic for: armv6 armv7 armv7s i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 16.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 16.0.0 (tapi-1600.0.11.8)
Library search paths:
	/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13
	/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc
	/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current
	/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib
	/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/lib/swift
Framework search paths:
	/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks
```

and the LC_RPATH entries from `otool -l` show:
```
Load command 11
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
Load command 12
          cmd LC_RPATH
      cmdsize 96
         path /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13 (offset 12)
Load command 13
          cmd LC_RPATH
      cmdsize 64
         path /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc (offset 12)
Load command 14
          cmd LC_RPATH
      cmdsize 64
         path /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current (offset 12)
```

### Apple-installed 'gcc' that is really clang 16

As far as I can tell, this does *not* use ld-classic; there are no LC_PATH entries in the resulting dylib:

```
$ printf 'void f(void){}' | gcc -xc - -dynamiclib -o libf.dylib -Wl,-v
@(#)PROGRAM:ld PROJECT:ld-1115.7.3
BUILD 07:38:57 Oct  4 2024
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
will use ld-classic for: armv6 armv7 armv7s i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 16.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 16.0.0 (tapi-1600.0.11.8)
Library search paths:
	/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
	/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/swift
Framework search paths:
	/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks
```

</details>

**Comment by Chrismarsh** [comment]
>updated our GCC recipe to use Iain's branch on macOS 15+, or apply equivalent patches s.t. it uses the new linker by default (like [homebrew does](https://github.com/Homebrew/homebrew-core/blob/e40f362220d2311aa48713988ec25ec6b8275bda/Formula/g/gcc.rb#L15-L18))

@haampie Spack's gcc when built on aarch64-darwin already uses the same patches as homebrew, e.g.,
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gcc/package.py#L437

are you aware of other patches that should be included? A few greps through homebrew shows a lot of `-ld_classic` being used. Indeed, I forgot to remove it from my customs flags, which is why I didn't reproduce @adamjstewart's vtk issue.

>Iain Sandoe's aarch64-darwin branch is still alive, which is now at GCC 13 with better support for the new linker.

Do you mean 14? https://github.com/iains/gcc-14-branch Or does the better support lag somewhat?

>I would suggest folks to use Iain's branch and consistently use the new linker instead.

Does his branch contain differences that aren't captured in the homebrew patch?

**Comment by haampie** [comment]
- https://github.com/iains/gcc-14-branch
- https://github.com/iains/gcc-13-branch
- https://github.com/iains/gcc-12-branch

The patches in Spack are outdated. See the readme of these repos regarding the linker.

**Comment by haampie** [comment]
I would suggest to close this after #47843. If anyone runs into errors about duplicate rpaths on macOS:

1. If you're using a (mixed) toolchain with GCC, install the latest GCC with latest patches.
2. Uninstall the package with the offending library.

**Comment by billsacks** [comment]
I retried my reproducer in https://github.com/spack/spack/issues/46506#issuecomment-2492650588 after #47843 (using a575fa85296af678048048f9811659147803a80b): I started with a fresh clone of spack and just did the gcc installation noted in that comment but the issue there still remains. (I tried both gcc 14.1 and the latest, 14.2.)

<details>
<summary>Similarly with @haampie 's suggested test</summary>

```
printf 'void f(void){}' | gcc -xc - -dynamiclib -o libf.dylib -Wl,-v
otool -l libf.dylib
```

still shows a duplicate RPATH (Load command 11 & Load command 14):

```
Load command 11
          cmd LC_RPATH
      cmdsize 128
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.2.0-vo3tk7k5uykuvfwzfgb6qani2r4inrra/lib (offset 12)
Load command 12
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
Load command 13
          cmd LC_RPATH
      cmdsize 168
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.2.0-vo3tk7k5uykuvfwzfgb6qani2r4inrra/lib/gcc/aarch64-apple-darwin23.6.0/14.2.0 (offset 12)
Load command 14
          cmd LC_RPATH
      cmdsize 128
         path /Users/sacks/spack/opt/spack/darwin-sonoma-m2/apple-clang-16.0.0/gcc-14.2.0-vo3tk7k5uykuvfwzfgb6qani2r4inrra/lib (offset 12)
```
</details>

If the recently-merged fix resolves the other Mac issues you're seeing, then no need for you to spend more time on this issue for my sake for now. (I can work around it myself, and will hope that Apple turns this back into just a warning in an upcoming xcode version.)

**Comment by adamjstewart** [comment]
Unfortunately seeing the same issue with Xcode 16.3/Apple Clang 17.0...

**Comment by Chrismarsh** [comment]
Yes, I'm back to the ld trick again. I haven't had the time to deep dive it. I had thought it was fixed but then it came back and I wasn't sure what I did wrong, if anything.
