### ISSUE TITLE
Problems building MVAPICH2 and Parallel NetCDF with Intel

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#991]
I'm now seeing intermittent problems building MVAPICH2 with Intel. I'll try:
```
spack install mvapich2 %intel +mrail
```
and it will crash during `make`. Then I'll run:
```
spack install hdf5@1.10.0 %intel +szip -cxx +mpi ^mvapich2+mrail
```
and MVAPICH2 will install without any trouble.

In addition, I'm unable to build parallel-netcdf with Intel and OpenMPI. Here are the `spack-build.out` and `config.log` files:

```
spack install parallel-netcdf %intel ^openmpi+tm+verbs
```
[spack-build.out](https://github.com/LLNL/spack/files/284643/spack-build.txt)
[config.log](https://github.com/LLNL/spack/files/284644/config.txt)
```
spack install parallel-netcdf %intel ^openmpi+tm+psm
```
[spack-build.out](https://github.com/LLNL/spack/files/284645/spack-build.txt)
[config.log](https://github.com/LLNL/spack/files/284646/config.txt)

@lee218llnl Any idea what's going on here? I removed all extraneous MPI installations from my paths and am using only the single `-Xlinker` line in my icc.cfg/icpc.cfg/ifort.cfg.

**Comment by lee218llnl** [comment]
@adamjstewart Nothing immediately stands out to me. Two suggestions, though. First, perhaps try disabling spack's parallel build (i.e. don't do a make -j #). I don't remember the exact semantics, but I believe you define parallel=False somewhere in the package.conf file. Second, perhaps trying building things outside of Spack, but using the spack-built Intel compiler just as a sanity check.

**Comment by adammoody** [comment]
Not sure how or where make is failing for you above, but there is a known problem with MV2-2.2 when using the Intel compiler and building the Fortran interface outside of the source tree.  See this thread:

http://mailman.cse.ohio-state.edu/pipermail/mvapich-discuss/2016-April/006046.html

This should be fixed in the next MV2-2.2 release.  Perhaps it will work if you fall back to MV2-2.0 or MV2-2.1?

**Comment by adamjstewart** [comment]
Can't tell if it helped or not, but I was able to build MVAPICH2 on my first try with `spack install -j 1 mvapich2` instead of on my second try.

As for PnetCDF, a non-parallel install didn't help. I'm going to try building outside of Spack.

**Comment by adamjstewart** [comment]
@alalazo Unfortunately #1059 didn't solve my problems here. Still can't build PnetCDF with OpenMPI and Intel. Going to try building things outside of Spack and contacting the developers for suggestions.

**Comment by alalazo** [comment]
@adamjstewart Unfortunately I don't have the time right now to fully debug this issue, but at a first glance these lines:
```
MPICC       = /blues/gpfs/home/software/spack/lib/spack/env/intel/icc
MPICXX      = /blues/gpfs/home/software/spack/lib/spack/env/intel/icpc
MPIF77      = /blues/gpfs/home/software/spack/lib/spack/env/intel/ifort
MPIF90      = /blues/gpfs/home/software/spack/lib/spack/env/intel/ifort
```
in your `spack-build.out` seem really suspicious... I think they should point to the MPI wrappers.

**Comment by alalazo** [comment]
@adamjstewart You may try modifying in the following way the function : 
```python
def setup_dependent_environment(self, spack_env, run_env, dependent_spec):
        spack_env.set('OMPI_CC', spack_cc)
        spack_env.set('OMPI_CXX', spack_cxx)
        spack_env.set('OMPI_FC', spack_fc)
        spack_env.set('OMPI_F77', spack_f77)

        # Do the same for MPICXX, MPIF90 and MPIF77
        spack_env.set('MPICC', join_path(self.prefix.bin, 'mpicc'))
        ...
```
in the `openmpi` package and see if it works

**Comment by adamjstewart** [comment]
Thanks @alalazo, I'll try it out!

**Comment by davydden** [comment]
@adamjstewart could it be that `parallel-netcdf` fails to pickup mpi compilers from 
```
args.extend(["--prefix=%s" % prefix,
                  "--with-mpi=%s" % spec['mpi'].prefix])
```
for whatever reason? 

Paths to compiler MPI wrappers IMHO should be 
```
MPICC=/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/intel-16.0.3/openmpi-1.10.2-qt4y5bjqwpqrtnpkpkl7ufbqpgqus3bt/bin/mpicc
```
and alike.

You can try specifying them in `parallel-netcdf` in addition to `--with-mpi=...`.

**Comment by adamjstewart** [comment]
@alalazo You've saved me once again, it worked! I'll submit a PR to add these variables. We should probably have them in every MPI package.

**Comment by alalazo** [comment]
@adamjstewart I agree they should be defined in every MPI provider.

 I also saw another "inconsistency" I would like to fix : 
```python
def setup_dependent_package(self, module, dep_spec):
        self.spec.mpicc = join_path(self.prefix.bin, 'mpicc')
        self.spec.mpicxx = join_path(self.prefix.bin, 'mpic++')
        self.spec.mpifc = join_path(self.prefix.bin, 'mpif90')
        self.spec.mpif77 = join_path(self.prefix.bin, 'mpif77')
```
This should either read : 
```python
def setup_dependent_package(self, module, dep_spec):
        module.mpicc = join_path(self.prefix.bin, 'mpicc')
        module.mpicxx = join_path(self.prefix.bin, 'mpic++')
        module.mpifc = join_path(self.prefix.bin, 'mpif90')
        module.mpif77 = join_path(self.prefix.bin, 'mpif77')
```
and fixed accordingly in the packages that use it or we should move the assignments:
```python
self.spec.mpicc = join_path(self.prefix.bin, 'mpicc')
self.spec.mpicxx = join_path(self.prefix.bin, 'mpic++')
self.spec.mpifc = join_path(self.prefix.bin, 'mpif90')
self.spec.mpif77 = join_path(self.prefix.bin, 'mpif77')
```
somewhere else in the MPI provider package... It feels weird to have attribute set for `self` within a hook that's there to modify other modules...

**Comment by tgamblin** [comment]
Fixed by #1103 (thanks to @adamjstewart, who said it was "solved", which github does not understand as well as "fixed")

**Comment by samcom12** [comment]
I fall on this issue for parallel-NetCDF with intel-mpi.
